<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-22T11:46:54 IST" name="Default suite" finished-at="2023-11-22T11:47:11 IST" duration-ms="16669">
    <groups>
    </groups>
    <test started-at="2023-11-22T11:46:54 IST" name="Default test" finished-at="2023-11-22T11:47:11 IST" duration-ms="16669">
      <class name="Task2">
        <test-method is-config="true" signature="setup()[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:46:54 IST" name="setup" finished-at="2023-11-22T11:47:03 IST" duration-ms="8250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginfail()[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:47:03 IST" name="loginfail" finished-at="2023-11-22T11:47:04 IST" duration-ms="1698" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://katalon-demo-cura.herokuapp.com/profile.php#login] but found [https://katalon-demo-cura.herokuapp.com/#appointment]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://katalon-demo-cura.herokuapp.com/profile.php#login] but found [https://katalon-demo-cura.herokuapp.com/#appointment]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Task2.loginfail(Task2.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginfail -->
        <test-method is-config="true" signature="failurescreenshot(org.testng.ITestResult)[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:47:04 IST" name="failurescreenshot" finished-at="2023-11-22T11:47:05 IST" duration-ms="410" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginfail status=FAILURE method=Task2.loginfail()[pri:0, instance:Task2@55141def] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failurescreenshot -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:47:05 IST" name="setup" finished-at="2023-11-22T11:47:09 IST" duration-ms="4658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logintest()[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:47:09 IST" name="logintest" finished-at="2023-11-22T11:47:11 IST" duration-ms="1451" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method is-config="true" signature="failurescreenshot(org.testng.ITestResult)[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:47:11 IST" name="failurescreenshot" finished-at="2023-11-22T11:47:11 IST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logintest status=SUCCESS method=Task2.logintest()[pri:0, instance:Task2@55141def] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failurescreenshot -->
        <test-method is-config="true" signature="shutdown()[pri:0, instance:Task2@55141def]" started-at="2023-11-22T11:47:11 IST" name="shutdown" finished-at="2023-11-22T11:47:11 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutdown -->
      </class> <!-- Task2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
